In [91]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()
import os 
import datetime
from datetime import timedelta

In [80]:
df_orig=pd.read_csv("RetailDailyPunches(09.30.18 to 01.01.19).csv")

In [81]:
df_orig['In Punch Date']=pd.to_datetime(df_orig['In Punch Date'] + ' ' + df_orig['In Punch Time'])
df_orig['Out Punch Date']=pd.to_datetime(df_orig['Out Punch Date'] + ' ' + df_orig['Out Punch Time'])
df_orig['Day']=df_orig['In Punch Date'].dt.strftime("%A")
df_orig['Duration']=df_orig['Out Punch Date'] - df_orig['In Punch Date']
df_orig['In Punch Date']=df_orig['In Punch Date'].apply(lambda dt: datetime.datetime(dt.year, dt.month, dt.day, dt.hour,15*(dt.minute // 15)))
df_orig['Out Punch Date']=df_orig['Out Punch Date'].apply(lambda dt: datetime.datetime(dt.year, dt.month, dt.day, dt.hour,15*(dt.minute // 15)))

In [ ]:
#df_orig['In Punch Date'] = pd.to_datetime(df_orig['In Punch Date'], format="%m/%d/%Y")
#df_orig['Out Punch Date'] = pd.to_datetime(df_orig['Out Punch Date'], format="%m/%d/%Y")
#df_orig['Day']=df_orig['In Punch Date'].dt.strftime("%A")
#df_orig['In Punch Time'] = pd.to_datetime(df_orig['In Punch Time'], format="%H:%M").dt.time
#df_orig['Out Punch Time'] = pd.to_datetime(df_orig['Out Punch Time'], format="%H:%M").dt.time

In [86]:
df_orig.tail(115)

,Store Number,EE Number,Name,Title,In Punch Date,In Punch Time,Out Punch Date,Out Punch Time,Day,Duration
296718,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-16 09:00:00,09:05,2018-12-16 11:00:00,11:03,Sunday,01:58:00
296719,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-17 12:00:00,12:05,2018-12-17 17:00:00,17:02,Monday,04:57:00
296720,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-17 17:30:00,17:41,2018-12-17 21:15:00,21:20,Monday,03:39:00
296721,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-18 12:00:00,12:05,2018-12-18 17:15:00,17:25,Tuesday,05:20:00
296722,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-18 17:45:00,17:58,2018-12-18 21:15:00,21:27,Tuesday,03:29:00
296723,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-21 13:45:00,13:58,2018-12-21 17:45:00,17:58,Friday,04:00:00
296724,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-21 18:15:00,18:28,2018-12-21 21:15:00,21:29,Friday,03:01:00
296725,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-22 13:00:00,13:00,2018-12-22 18:00:00,18:12,Saturday,05:12:00
296726,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-22 18:30:00,18:42,2018-12-22 21:15:00,21:17,Saturday,02:35:00
296727,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-26 09:30:00,09:39,2018-12-26 15:00:00,15:02,Wednesday,05:23:00
296728,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-27 13:00:00,13:03,2018-12-27 18:15:00,18:16,Thursday,05:13:00
296729,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-27 18:45:00,18:46,2018-12-27 21:15:00,21:23,Thursday,02:37:00
296730,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-28 11:45:00,11:59,2018-12-28 17:00:00,17:00,Friday,05:01:00
296731,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-28 17:30:00,17:30,2018-12-28 21:15:00,21:27,Friday,03:57:00
296732,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-29 13:00:00,13:04,2018-12-29 17:00:00,17:13,Saturday,04:09:00
296733,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-29 17:30:00,17:43,2018-12-29 21:15:00,21:29,Saturday,03:46:00
296734,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-30 10:30:00,10:37,2018-12-30 14:00:00,14:03,Sunday,03:26:00
296735,1502,48125,"Vaught, Donnie",Key Holder full time,2018-12-30 14:30:00,14:33,2018-12-30 18:15:00,18:22,Sunday,03:49:00
296736,1502,48601,"Dauthe, Derek J",Sales Associate,2018-10-19 13:00:00,13:00,2018-10-19 17:00:00,17:00,Friday,04:00:00
296737,1502,48601,"Dauthe, Derek J",Sales Associate,2018-10-20 11:00:00,11:04,2018-10-20 13:00:00,13:03,Saturday,01:59:00
296738,1502,48601,"Dauthe, Derek J",Sales Associate,2018-10-25 13:00:00,13:01,2018-10-25 18:00:00,18:01,Thursday,05:00:00
296739,1502,48601,"Dauthe, Derek J",Sales Associate,2018-10-26 16:00:00,16:06,2018-10-26 21:15:00,21:23,Friday,05:17:00
296740,1502,48601,"Dauthe, Derek J",Sales Associate,2018-10-27 13:00:00,13:05,2018-10-27 18:00:00,18:00,Saturday,04:55:00
296741,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-01 12:00:00,12:01,2018-11-01 17:00:00,17:08,Thursday,05:07:00
296742,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-03 15:00:00,15:01,2018-11-03 18:15:00,18:16,Saturday,03:15:00
296743,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-03 18:45:00,18:48,2018-11-03 21:15:00,21:28,Saturday,02:40:00
296744,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-04 13:00:00,13:00,2018-11-04 16:15:00,16:26,Sunday,03:26:00
296745,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-04 16:45:00,16:56,2018-11-04 18:15:00,18:28,Sunday,01:32:00
296746,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-09 16:00:00,16:02,2018-11-09 21:15:00,21:25,Friday,05:23:00
296747,1502,48601,"Dauthe, Derek J",Sales Associate,2018-11-15 16:00:00,16:00,2018-11-15 21:15:00,21:25,Thursday,05:25:00
...,...,...,...,...,...,...,...,...,...,...
296803,1502,48613,"Harris, Casey M",Key Holder part time,2018-11-28 13:00:00,13:01,2018-11-28 17:30:00,17:35,Wednesday,04:34:00
296804,1502,48613,"Harris, Casey M",Key Holder part time,2018-11-28 18:00:00,18:06,2018-11-28 21:15:00,21:16,Wednesday,03:10:00
296805,1502,48613,"Harris, Casey M",Key Holder part time,2018-11-30 15:00:00,15:00,2018-11-30 17:30:00,17:39,Friday,02:39:00
296806,1502,48613,"Harris, Casey M",Key Holder part time,2018-11-30 18:00:00,18:11,2018-11-30 21:30:00,21:30,Friday,03:19:00
296807,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-03 15:00:00,15:00,2018-12-03 16:00:00,16:00,Monday,01:00:00
296808,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-03 16:45:00,16:59,2018-12-03 21:30:00,21:31,Monday,04:32:00
296809,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-05 10:00:00,10:03,2018-12-05 15:00:00,15:12,Wednesday,05:09:00
296810,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-05 15:30:00,15:42,2018-12-05 16:00:00,16:14,Wednesday,00:32:00
296811,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-07 12:00:00,12:02,2018-12-07 17:00:00,17:11,Friday,05:09:00
296812,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-12 13:00:00,13:01,2018-12-12 18:45:00,18:50,Wednesday,05:49:00
296813,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-12 19:15:00,19:21,2018-12-12 21:15:00,21:23,Wednesday,02:02:00
296814,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-14 09:00:00,09:05,2018-12-14 14:00:00,14:04,Friday,04:59:00
296815,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-15 15:45:00,15:59,2018-12-15 18:45:00,18:45,Saturday,02:46:00
296816,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-15 19:15:00,19:16,2018-12-15 21:15:00,21:18,Saturday,02:02:00
296817,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-16 09:00:00,09:01,2018-12-16 13:15:00,13:19,Sunday,04:18:00
296818,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-16 13:45:00,13:50,2018-12-16 18:30:00,18:34,Sunday,04:44:00
296819,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-19 12:45:00,12:59,2018-12-19 17:15:00,17:20,Wednesday,04:21:00
296820,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-19 17:45:00,17:50,2018-12-19 21:15:00,21:17,Wednesday,03:27:00
296821,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-20 09:15:00,09:28,2018-12-20 14:00:00,14:14,Thursday,04:46:00
296822,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-20 14:45:00,14:47,2018-12-20 15:00:00,15:01,Thursday,00:14:00
296823,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-22 09:15:00,09:28,2018-12-22 14:45:00,14:45,Saturday,05:17:00
296824,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-22 15:15:00,15:17,2018-12-22 17:00:00,17:02,Saturday,01:45:00
296825,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-24 11:45:00,11:59,2018-12-24 15:30:00,15:33,Monday,03:34:00
296826,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-24 16:00:00,16:05,2018-12-24 18:15:00,18:20,Monday,02:15:00
296827,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-26 14:45:00,14:56,2018-12-26 20:00:00,20:01,Wednesday,05:05:00
296828,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-26 20:30:00,20:32,2018-12-26 21:15:00,21:22,Wednesday,00:50:00
296829,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-28 09:30:00,09:33,2018-12-28 14:45:00,14:45,Friday,05:12:00
296830,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-28 15:15:00,15:16,2018-12-28 17:45:00,17:59,Friday,02:43:00
296831,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-29 09:15:00,09:27,2018-12-29 14:00:00,14:00,Saturday,04:33:00
296832,1502,48613,"Harris, Casey M",Key Holder part time,2018-12-30 13:45:00,13:58,2018-12-30 18:15:00,18:20,Sunday,04:22:00

In [92]:
punchTimesDF = pd.read_csv(r"RetailDailyPunches(09.30.18 to 01.01.19).csv", index_col=None)
 
punchTimesDF.rename(columns= {'In Punch Date':'In_Date', 'In Punch Time':'In_Time', 'Out Punch Date':'Out_Date',
                                  'Out Punch Time':'Out_Time','Store Number':'Store_Number', 'EE Number':'EE_Number'}, inplace=True)
title_dictionary = {'Key Holder full time':'Key Holder', 'Key Holder Part Time':'Key Holder', 'Key Holder Part time':'Key Holder',
            'Key Holder part time':'Key Holder', 'Key Holder Full Time':'Key Holder', 'Sr. Sales Associate':'Sales Associate'}
 
punchTimesDF.replace({"Title": title_dictionary}, inplace=True)
 
 
#Combining date and hours into a single colummn
punchTimesDF['in'] = punchTimesDF['In_Date'] + ' ' + punchTimesDF['In_Time']
 
punchTimesDF['out'] = punchTimesDF['Out_Date'] + ' ' + punchTimesDF['Out_Time']
 
#Converting to datetime
 
punchTimesDF['in'] = pd.to_datetime(punchTimesDF['in'])
punchTimesDF['out'] = pd.to_datetime(punchTimesDF['out'])
 
 
#calculating the hours worked from our raw times
punchTimesDF['raw_hours'] = punchTimesDF['out'] - punchTimesDF['in']
 
#ROunding the in and out dates to the nearest half hour
 
def round_minutes(dt, direction, resolution):
    new_minute = (dt.minute // resolution + (1 if direction == 'up' else 0)) * resolution
    return dt + timedelta(minutes=new_minute - dt.minute)
 
 
punchTimesDF['rounded_in'] = punchTimesDF['in'].apply(lambda x: round_minutes(x, 'up', 30))
 
punchTimesDF['rounded_out'] = punchTimesDF['out'].apply(lambda x: round_minutes(x, 'down', 30))
 
 
 
#calcuatling the hours worked from our rounded times
 
punchTimesDF['rounded_hours'] = punchTimesDF['rounded_out'] - punchTimesDF['rounded_in']

In [93]:
punchTimesDF.head()

,Store_Number,EE_Number,Name,Title,In_Date,In_Time,Out_Date,Out_Time,in,out,raw_hours,rounded_in,rounded_out,rounded_hours
0,1,34460,"Polanco, Yanardy",Assistant Manager,10/01/2018,07:18,10/01/2018,13:47,2018-10-01 07:18:00,2018-10-01 13:47:00,06:29:00,2018-10-01 07:30:00,2018-10-01 13:30:00,06:00:00
1,1,34460,"Polanco, Yanardy",Assistant Manager,10/01/2018,14:21,10/01/2018,16:41,2018-10-01 14:21:00,2018-10-01 16:41:00,02:20:00,2018-10-01 14:30:00,2018-10-01 16:30:00,02:00:00
2,1,34460,"Polanco, Yanardy",Assistant Manager,10/02/2018,06:46,10/02/2018,12:02,2018-10-02 06:46:00,2018-10-02 12:02:00,05:16:00,2018-10-02 07:00:00,2018-10-02 12:00:00,05:00:00
3,1,34460,"Polanco, Yanardy",Assistant Manager,10/02/2018,12:50,10/02/2018,16:05,2018-10-02 12:50:00,2018-10-02 16:05:00,03:15:00,2018-10-02 13:00:00,2018-10-02 16:00:00,03:00:00
4,1,34460,"Polanco, Yanardy",Assistant Manager,10/03/2018,13:06,10/03/2018,15:03,2018-10-03 13:06:00,2018-10-03 15:03:00,01:57:00,2018-10-03 13:30:00,2018-10-03 15:00:00,01:30:00

In [94]:
df_orig.head()

,Store Number,EE Number,Name,Title,In Punch Date,In Punch Time,Out Punch Date,Out Punch Time,Day,Duration
0,1,34460,"Polanco, Yanardy",Assistant Manager,2018-10-01 07:15:00,07:18,2018-10-01 13:45:00,13:47,Monday,06:29:00
1,1,34460,"Polanco, Yanardy",Assistant Manager,2018-10-01 14:15:00,14:21,2018-10-01 16:30:00,16:41,Monday,02:20:00
2,1,34460,"Polanco, Yanardy",Assistant Manager,2018-10-02 06:45:00,06:46,2018-10-02 12:00:00,12:02,Tuesday,05:16:00
3,1,34460,"Polanco, Yanardy",Assistant Manager,2018-10-02 12:45:00,12:50,2018-10-02 16:00:00,16:05,Tuesday,03:15:00
4,1,34460,"Polanco, Yanardy",Assistant Manager,2018-10-03 13:00:00,13:06,2018-10-03 15:00:00,15:03,Wednesday,01:57:00